version: 1.0.{build}
image: Visual Studio 2019
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: SpellWork\bin
  name: SpellWork
